#!/usr/bin/env ruby

# frozen_string_literal: true

require 'optparse'
require 'json'

class Task
  attr_reader :id, :at, :status

  STATUS_PENDING = 'PENDING'
  STATUS_IN_PROGRESS = 'IN PROGRESS'
  STATUS_DONE = 'DONE'

  def initialize(id:, task:, status:)
    @id = id
    @task = task
    @status = status
    @at = Time.at(id)
  end

  def completed?
    @status == STATUS_DONE
  end

  def complete!
    @status = STATUS_DONE
    @at = Time.now
  end

  def start!
    @status = STATUS_IN_PROGRESS
    @at = Time.now
  end

  def revert!
    @status = STATUS_PENDING
    @at = Time.now
  end

  def to_s
    @task
  end
end

class Printer
  def initialize(out)
    @out = out
    @tasks = []
  end

  def print(tasks)
    @tasks = tasks
    print_banner
    @tasks.each do |_, task|
      print_task(task)
    end
  end

  private

  def print_banner
    if @tasks.empty?
      @out.puts 'No Tasks Here'
      return
    end
    @out.puts 'Tasks'
  end

  def print_task(task)
    @out.puts("|#{task.status.ljust(11)} | #{task.id} | #{task.to_s.ljust(longest_task_length)} | #{task.at}|")
  end

  def longest_task_length
    @longest_task_length ||= @tasks.values.sort { |a, b| a.to_s.length <=> b.to_s.length }.last.to_s.length
  end
end

class RecordNotFoundError < StandardError; end

class TaskManager
  STORAGE = ::File.join(ENV['HOME'], '.todos')

  def initialize(printer)
    @printer = printer
    load_tasks
  end

  def add(task)
    id = Time.now.to_i
    @tasks[id] = Task.new(id: id, task: task, status: Task::STATUS_PENDING)
    store_tasks
  end

  def start(task_id)
    find(task_id).start!
    store_tasks
  end

  def complete(task_id)
    find(task_id).complete!
    store_tasks
  end

  def revert(task_id)
    find(task_id).revert!
    store_tasks
  end

  def delete(task_id)
    @tasks.delete(task_id)
    store_tasks
  end

  def print_all_tasks
    @printer.print(@tasks)
  end

  def query(q)
    @printer.print(@tasks.reject{|_, task| task.to_s.scan(q).empty?})
  end

  def print_pending_tasks
    @printer.print(@tasks.reject{|_, task| task.completed? })
  end

  def cleanup
    @tasks = {}
    store_tasks
  end

  private

  def find(task_id)
    @tasks.fetch(task_id)
  rescue KeyError
    raise RecordNotFoundError
  end

  def load_tasks
    @tasks = {}
    return unless File.exist?(STORAGE)

    data = JSON.parse(File.read(STORAGE))
    data.each do |key, val|
      @tasks[key.to_i] = Task.new(id: key.to_i, task: val['task'], status: val['status'])
    end
  end

  def store_tasks
    data = {}
    @tasks.each do |id, task|
      data[id] = {
        task: task.to_s,
        status: task.status,
      }
    end
    File.open(STORAGE, 'w') do |f|
      f.write JSON.generate(data)
    end
  end
end

@task_manager = TaskManager.new(Printer.new($stdout))

OptionParser.new do |opts|
  opts.banner = 'Usage: todo [options] [task]'

  opts.on('-a', '--all', 'Print all tasks') do
    @task_manager.print_all_tasks
    exit
  end

  opts.on('-c', '--complete TASK_ID', Integer, 'Complete task') do |task_id|
    puts "Marking as completed task: #{task_id}"
    begin
      @task_manager.complete(task_id)
    rescue RecordNotFoundError => _
      puts "Task not found" 
    end
    exit
  end

  opts.on('-d', '--delete TASK_ID', Integer, 'Delete task') do |task_id|
    puts "Deleting task: #{task_id}"
    @task_manager.delete(task_id)
    exit
  end

  opts.on('-k', '--cleanup', 'Drop everyting') do
    @task_manager.cleanup
    exit
  end

  opts.on('-q', '--query QUERY', String, 'Search in todo list') do |q|
    @task_manager.query(q)
    exit
  end

  opts.on('-r', '--revert TASK_ID', Integer, 'Revert task') do |task_id|
    puts "Reverting task: #{task_id}"
    begin
      @task_manager.revert(task_id)
    rescue RecordNotFoundError => _
      puts "Task not found" 
    end
    exit
  end

  opts.on('-s', '--start TASK_ID', Integer, 'Move task status in progress') do |task_id|
    puts "Moving task in progress: #{task_id}"
    begin
      @task_manager.start(task_id)
    rescue RecordNotFoundError => _
      puts "Task not found" 
    end
    exit
  end
end.parse!

if ARGV.count > 0
  task = ARGV.join(" ")
  puts "Inserting new task: #{task}"
  @task_manager.add(task)
else
  @task_manager.print_pending_tasks
end
